isfa:
  full: "ISFA Standard"
  short: ISFA
  sort: 0
  resources:
    "String Figure Terminology (PDF)": http://isfa.org/sfotm/terminology/string_figure_terminology.pdf
    "Nomenclature": http://www.isfa.org/arctic/n.htm

mizz:
  full: "Mizz Code"
  sort: 1
  resources:
    "The basics of Mizz code in picture form": http://home.p07.itscom.net/nenemei/v2/index.html
    "Quick Reference": http://stringfigures.info/mizz-quickref.html
    "Yahoo! Group": http://groups.yahoo.com/group/mizz-code/

sfn:
  full: "String Figure Notation"
  short: "SFN"
  sort: 2
  resources:
    "A Shorthand Notation for Recording String Figures": http://www.alysion.org/figures/notation.htm

fsfn:
  full: "Formal String Figure Notation"
  short: "FSFN"
  sort: 3
  resources:
    "An attempt to formalise notation for String Figures": http://www.ben-daglish.net/string/

cfj:
  full: "Jayne's Notation"
  short: "CFJ"
  sort: 4
  resources:
    "String Figures and How to Make Them, Chapter 1": http://www.stringfigures.info/cfj/chapter-01.html

rivers-haddon:
  full: "Rivers-Haddon Notation"
  short: "Rivers-Haddon"
  sort: 5
  resources:
    "Man, Volume 2, No. 109, \"A Method of Recording String Figures and Tricks\"": http://books.google.com/books?id=yRP0I0s8QdEC&pg=PA146

prose:
  full: "Other Prose Notation"
  short: "Prose"
  sort: 6

other:
  full: "Other Notation"
  short: "Other"
  sort: 7
